name = "xvc-agent2"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[limits]
subrequest_limit = 1000

[[d1_databases]]
binding = "DB"
database_name = "xvc-agent2"
database_id = "0ee12134-09c7-496a-9013-ed3128aae3c2"

[[r2_buckets]]
binding = "FILES"
bucket_name = "xvc-agent2-files"

[assets]
directory = "./public"
binding = "ASSETS"

[triggers]
crons = ["*/5 * * * *"]
